export const natureOfServiceOptions = [
  "26 - - Transporte internacional de cargas efetuado por empresas nacionais;",
  "39 - - Administração, locação ou cessão de bens imóveis, móveis e direitos de qualquer natureza;",
  "22 - - Álcool etílico hidratado inclusive para fins carburantes, adquirido diretamente do produtor, importador ou distribuidor de que trata o art. 20 Biodisel adquirido de produtor ou importador, de que trata o art 21.",
  "13 - - Alimentação;",
  `25 - - Biodisel adquirido de produtor detentor regular do selo "combustível social" Fabricado a partir de mamona ou fruto, caroço ou amêndoa de Salma produzidos nas regiões norte e nordeste e no semiárido, por Agricultor familiar enquadrado no Programa nacional de fortalecimento da Agricultura Familiar(Pronaf).`,
  "16 - - Construção Civil por empreitada com emprego de materiais;",
  "34 - - Correio e telégrafos;",
  "27 - - Estaleiros navais brasileiros nas atividades de construção, conservação, modernização, conversão e reparo de embarcações pré-registradas no REB, instituído pela Lei n° 9.432, de 08 de janeiro de 1997;",
  "40 - - Factoring",
  "23 - - Gasolina, exceto gasolina de aviação, óleo diesel, gás liquefeito de petróleo(GLP), derivados de petróleo ou de gás natural e querosene de aviação adquiridos de dis-distribuidores e comerciantes varejistas; Álcool etílico hidratado nacional, inclusive para fins carburantes adquirido e comerciante varejista;",
  "21 - - Gasolina, inclusive de aviação, óleo diesel, gás liquefeito de petróleo(GLP), combustíveis derivados de petróleo ou de gás natural, querosne de aviação (QAV) e demais produtos derivados de petrólo, adquiridos de refinarias de petróleo, de demais produtores, de importadores, de distribuidor ou varejista, pelos orgãos da administração publica de que trata caput do art. 19;",
  "38 - - Intermediação de negócios;",
  "36 - - Limpeza;",
  "37 - - Locação de mão-de-obra;",
  "20 - - Mercadorias e bens em geral.",
  "8 - - Passagens aéreas, rodoviárias e demais serviços de transporte de passageiros, inclusive, tarifa de embarque, exceto as relacionadas no código 8850.",
  `30 - - Produtos de que se tratam as alíneas "c" a "k" do inciso I do art. 5°, Outros produtos ou serviços beneficiados com isenção, não incidência ou alíquotas zero da Cofins e da Contribuição para PIS/PASEP, observado o disposto no $ 5° do art. 2°.`,
  "32 - - Serviços de abastecimento de água;",
  "33 - - Telefone;",
  "19 - - Transporte de cargas, exceto os relacionados no código 8767; Produtos farmaceuticos, de perfumaria, de toucador ou de higiene pessoal adquiridos de produtor, importador, distribuidor ou varejista, exceto se relacionados no código 8767;",
  "9 - - Transporte internacional de passageiros efetuado;",
  "35 - - Vigilância;",
  "41 - - Plano de saúde humano, veterinário ou odontológico com valores fixos por servidor, por emprego ou por animal;",
  "31 - - Seguro de Saúde.",
  "18 - - Serviço de auxilio diagnóstico e terapia, patologia clínica, imagenologia, natomia patológica e citopatológia, medicina nuclear e análises e antologias clínicas de que trata o art. 31",
  "24 - Biodiesel adquirido de distribuidores e comerciantes varejistas;",
  "42 - Demais serviços",
  "43 - DEMAIS serviços",
  "14 - Energia elétrica",
  "29 - Produtos a que se refere o $ 2° do art. 22;",
  "28 - Produtos farmacêuticos, de perfumaria, de toucador e de higiene pessoal a que se refere o $ 1° do art 22, adquiridos de distribuidores e de comercientes e varejistas;",
  "44 - Serviõs Pessoais Prestados por Associação de Cooprativas de Trabalhos"
]